[metadata]
name = maskdino
version = 0.0.0
description = Detectron2 based framework for object detection and segmentation
long_description = file: README.md
author = IDEA Research
author_email = todo
license = Apache-2.0
url = https://github.com/agyoungs/MaskDINO

[options]
packages = find:
python_requires = >=3.6
install_requires =
    cython
    scipy
    shapely
    timm
    h5py
    submitit
    scikit-image
    numpy
    #opencv-python
    #pytorch >=1.9 installed with matching torchvision

[options.extras_require]
dev =
    pytest
    black
    flake8
    isort

[options.packages.find]
where = .
