[metadata]
name = maskdino
version = 0.0.0
description = Detectron2 based framework for object detection and segmentation
author = Feng Li and Hao Zhang and Huaizhe xu and Shilong Liu and Lei Zhang and Lionel M. Ni and Heung-Yeung Shum
author_email = 
license = Apache license V2.0
url = https://github.com/agyoungs/MaskDINO

[options]
packages = find:
python_requires = >=3.6
install_requires =
    cython
    scipy
    shapely
    timm
    h5py
    submitit
    scikit-image
    opencv-python

#pytorch >=1.9 installed with matching torchvision
